server:
  port: 8089
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

auth:
  jwt:
    pubKeyPath: D:\\tmp\\rsa.pub
    priKeyPath: D:\\tmp\\rsa.pri
    secret: zhangqikdkkkkk
    expire: 30 # \u65F6\u95F4\u5355\u4F4D\u4E3A\u5206\u949F
    cookieName: Gmall_Token
